/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.qoopo.engine3d.editor.entidad.componentes.fisica.colision;

import javax.swing.DefaultComboBoxModel;
import net.qoopo.engine3d.componentes.QComponente;
import net.qoopo.engine3d.componentes.fisica.colisiones.detectores.contenedores.mallas.QColisionMallaConvexa;
import net.qoopo.engine3d.componentes.geometria.QGeometria;

/**
 *
 * @author alberto
 */
public class PnlColisionMallaConvexa extends javax.swing.JPanel {

    private QColisionMallaConvexa forma;

    /**
     * Creates new form PnlCubo
     */
    public PnlColisionMallaConvexa(QColisionMallaConvexa forma) {
        initComponents();
        this.forma = forma;
        DefaultComboBoxModel modelo = new DefaultComboBoxModel<>();
        for (QComponente comp : forma.entidad.getComponentes()) {
            if (comp instanceof QGeometria) {
                modelo.addElement(((QGeometria) comp).nombre);
            }
        }
        cboMalla.setModel(modelo);
        cboMalla.setSelectedItem(forma.getMalla().nombre);
//        txtRadio.setText(String.valueOf(forma.getRadio()));
    }

    private void aplicarCambios() {
//        forma.setRadio(Float.parseFloat(txtRadio.getText()));
        for (QComponente comp : forma.entidad.getComponentes()) {
            if (comp instanceof QGeometria) {
                if (((QGeometria) comp).nombre.equals(cboMalla.getSelectedItem().toString())) {
                    forma.setMalla((QGeometria) comp);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboMalla = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Colisión Malla Convexa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 9))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel1.setText("Malla:");

        cboMalla.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        cboMalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMallaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboMalla, 0, 101, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(cboMalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboMallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMallaActionPerformed
        aplicarCambios();        // TODO add your handling code here:
    }//GEN-LAST:event_cboMallaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboMalla;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
