/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.qoopo.engine3d.editor.entidad.componentes.animacion;

import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import net.qoopo.engine3d.componentes.QUtilComponentes;
import net.qoopo.engine3d.componentes.animacion.QCompAlmacenAnimaciones;
import net.qoopo.engine3d.componentes.animacion.QComponenteAnimacion;

/**
 *
 * @author alberto
 */
public class PnlAlamacenAnimacion extends javax.swing.JPanel {
    
    private DecimalFormat df = new DecimalFormat("0.00");
    
    private QCompAlmacenAnimaciones almacen;
    private QComponenteAnimacion animacionActiva;

    /**
     * Creates new form PnlAlamacenAnimacion
     */
    public PnlAlamacenAnimacion(QCompAlmacenAnimaciones almacen) {
        initComponents();
        lstAnimacion.setModel(new DefaultListModel<>());
        this.almacen = almacen;
        desplegarAlmacen();
    }
    
    private void desplegarAlmacen() {
        DefaultListModel modelAnim = (DefaultListModel) lstAnimacion.getModel();
        modelAnim.clear();
        for (QComponenteAnimacion animacion : almacen.getAnimaciones().values()) {
            modelAnim.addElement(animacion.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAnimacion = new javax.swing.JList<>();
        btnAnimActualIniciar = new javax.swing.JButton();
        btnAnimActualDetener = new javax.swing.JButton();
        btnEliminarAnimacion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblNombreAnimacion = new javax.swing.JLabel();
        lblAnimDuracion = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblAnimFrames = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        chkLoop = new javax.swing.JCheckBox();

        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Almacen Animación"));

        lstAnimacion.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lstAnimacion.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAnimacionValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstAnimacion);

        btnAnimActualIniciar.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        btnAnimActualIniciar.setText("Iniciar");
        btnAnimActualIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimActualIniciarActionPerformed(evt);
            }
        });

        btnAnimActualDetener.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        btnAnimActualDetener.setText("Detener");
        btnAnimActualDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimActualDetenerActionPerformed(evt);
            }
        });

        btnEliminarAnimacion.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        btnEliminarAnimacion.setText("Eliminar");
        btnEliminarAnimacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAnimacionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel4.setText("Nombre:");

        lblNombreAnimacion.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lblNombreAnimacion.setText("0");

        lblAnimDuracion.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lblAnimDuracion.setText("0 s");

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel22.setText("Duración:");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel23.setText("Frames:");

        lblAnimFrames.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lblAnimFrames.setText("0");

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel24.setText("Loop:");

        chkLoop.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        chkLoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLoopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblAnimDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addComponent(lblAnimFrames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(chkLoop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreAnimacion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnimActualIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnimActualDetener)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarAnimacion)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnimActualIniciar)
                    .addComponent(btnAnimActualDetener)
                    .addComponent(btnEliminarAnimacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNombreAnimacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(lblAnimDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblAnimFrames))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(chkLoop)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstAnimacionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAnimacionValueChanged
        try {
            if (lstAnimacion.getSelectedIndex() >= 0) {
                animacionActiva = QUtilComponentes.getAlmacenAnimaciones(almacen.entidad).getAnimacion(lstAnimacion.getSelectedValue());
                if (animacionActiva != null) {
                    lblAnimDuracion.setText(df.format(animacionActiva.getDuracion()) + " s");
                    lblAnimFrames.setText("" + animacionActiva.getListaFrames().size());
                    lblNombreAnimacion.setText(animacionActiva.getNombre());
                    chkLoop.setSelected(animacionActiva.isLoop());
                    
                }
                //            activeMaterial = editingMaterial.get(lstMaterials.getSelectedIndex());
                //            pnlMaterialControl.setVisible(true);
                //            populateMaterialControl(activeMaterial);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lstAnimacionValueChanged

    private void btnAnimActualIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimActualIniciarActionPerformed
        
        if (animacionActiva != null) {
            QUtilComponentes.eliminarComponenteAnimacion(almacen.entidad);
            almacen.entidad.agregarComponente(animacionActiva);
        }
    }//GEN-LAST:event_btnAnimActualIniciarActionPerformed

    private void btnAnimActualDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimActualDetenerActionPerformed
        QUtilComponentes.eliminarComponenteAnimacion(almacen.entidad);
    }//GEN-LAST:event_btnAnimActualDetenerActionPerformed

    private void btnEliminarAnimacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAnimacionActionPerformed
        if (animacionActiva != null) {
            QUtilComponentes.getAlmacenAnimaciones(almacen.entidad).eliminarAnimacion(lstAnimacion.getSelectedValue());
            
        }
    }//GEN-LAST:event_btnEliminarAnimacionActionPerformed

    private void chkLoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLoopActionPerformed
        if (animacionActiva != null) {
            animacionActiva.setLoop(chkLoop.isSelected());
        }
    }//GEN-LAST:event_chkLoopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimActualDetener;
    private javax.swing.JButton btnAnimActualIniciar;
    private javax.swing.JButton btnEliminarAnimacion;
    private javax.swing.JCheckBox chkLoop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnimDuracion;
    private javax.swing.JLabel lblAnimFrames;
    private javax.swing.JLabel lblNombreAnimacion;
    private javax.swing.JList<String> lstAnimacion;
    // End of variables declaration//GEN-END:variables
}
