/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.qoopo.engine3d.editor.entidad.componentes.terreno;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.qoopo.engine3d.componentes.QUtilComponentes;
import net.qoopo.engine3d.componentes.terreno.QTerreno;
import net.qoopo.engine3d.core.util.QGlobal;
import net.qoopo.engine3d.core.textura.QTextura;
import net.qoopo.engine3d.core.util.ImgUtil;
import net.qoopo.engine3d.editor.Principal;
import net.qoopo.engine3d.editor.util.ImagePreviewPanel;

/**
 *
 * @author alberto
 */
public class PnlTerreno extends javax.swing.JPanel {

    private final JFileChooser chooser = new JFileChooser();
    private final ImagePreviewPanel preview = new ImagePreviewPanel();

    private QTerreno terreno;
    private BufferedImage imagen;
    private BufferedImage imagen2;// para la vista previa
    private BufferedImage mapaDifusoActual;// para la vista previa
    private BufferedImage mapaNormalActual;// para la vista previa

    private QTextura textura;
    private QTextura texturaNormal;

    /*
    BufferedImage imagen, float tamanioCelda, float minY, float maxY, QTextura textura, float razonTextura, int offset
     */
    /**
     * Creates new form PnlCubo
     */
    public PnlTerreno(QTerreno terreno) {
        initComponents();

        chooser.setCurrentDirectory(new File(QGlobal.RECURSOS));

        chooser.setAccessory(preview);
        chooser.addPropertyChangeListener(preview);

        textura = new QTextura();
        this.terreno = terreno;

    }

    private void aplicarCambios() {
        //elimino los componentes de geometria que se haya generado anteriormente
        QUtilComponentes.eliminarComponenteGeometria(terreno.entidad);
        if (textura != null) {
            textura.setMuestrasU(Float.valueOf(txtMU_Difusa.getText()));
            textura.setMuestrasV(Float.valueOf(txtMV_Difusa.getText()));
        }
        if (imagen != null) {
            terreno.generar(imagen, Float.valueOf(txtTamCelda.getText()), Float.valueOf(txtMinY.getText()), Float.valueOf(txtMaxY.getText()), textura, Integer.valueOf(txtOffset.getText()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAplicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlTexture = new javax.swing.JPanel() {
            public void paint(Graphics g) {
                super.paint(g);
                if (imagen2 != null)
                g.drawImage(imagen2, 0, 0, this);
            }
        };
        btnCargar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTamCelda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMinY = new javax.swing.JTextField();
        txtMaxY = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOffset = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlMapaDifuso = new javax.swing.JPanel() {
            public void paint(Graphics g) {
                super.paint(g);
                if (mapaDifusoActual != null)
                g.drawImage(mapaDifusoActual, 0, 0, this);
            }
        };
        txtMU_Difusa = new javax.swing.JTextField();
        btnSetMapaDifuso = new javax.swing.JButton();
        btnEliminaMapaDifuso = new javax.swing.JButton();
        txtMV_Difusa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pnlNormalMap = new javax.swing.JPanel() {
            public void paint(Graphics g) {
                super.paint(g);
                if (mapaNormalActual != null)
                g.drawImage(mapaNormalActual, 0, 0, this);
            }
        };
        btnNormalMap = new javax.swing.JButton();
        btnEliminaMapaNormal = new javax.swing.JButton();
        txtMU_Normal = new javax.swing.JTextField();
        txtMV_Normal = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Terreno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 9))); // NOI18N

        btnAplicar.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel1.setText("Imagen:");

        pnlTexture.setBackground(new java.awt.Color(0, 0, 0));
        pnlTexture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTextureMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTextureLayout = new javax.swing.GroupLayout(pnlTexture);
        pnlTexture.setLayout(pnlTextureLayout);
        pnlTextureLayout.setHorizontalGroup(
            pnlTextureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTextureLayout.setVerticalGroup(
            pnlTextureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        btnCargar.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel2.setText("Tam. Celda:");

        txtTamCelda.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        txtTamCelda.setText("1");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel3.setText("Min. Y:");

        txtMinY.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        txtMinY.setText("1");

        txtMaxY.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        txtMaxY.setText("10");
        txtMaxY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxYActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel4.setText("Máx. Y:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel5.setText("Offset:");

        txtOffset.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        txtOffset.setText("5");
        txtOffset.setToolTipText("Cantidad de pixeles a saltar para el muestreo");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Texturas");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel10.setText("Difuso:");

        pnlMapaDifuso.setBackground(new java.awt.Color(0, 0, 0));
        pnlMapaDifuso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMapaDifusoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMapaDifusoLayout = new javax.swing.GroupLayout(pnlMapaDifuso);
        pnlMapaDifuso.setLayout(pnlMapaDifusoLayout);
        pnlMapaDifusoLayout.setHorizontalGroup(
            pnlMapaDifusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMapaDifusoLayout.setVerticalGroup(
            pnlMapaDifusoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        txtMU_Difusa.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        txtMU_Difusa.setText("1");
        txtMU_Difusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMU_DifusaActionPerformed(evt);
            }
        });

        btnSetMapaDifuso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/text_16.png"))); // NOI18N
        btnSetMapaDifuso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetMapaDifusoActionPerformed(evt);
            }
        });

        btnEliminaMapaDifuso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/delete_16.png"))); // NOI18N
        btnEliminaMapaDifuso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaMapaDifusoActionPerformed(evt);
            }
        });

        txtMV_Difusa.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        txtMV_Difusa.setText("1");
        txtMV_Difusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMV_DifusaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel11.setText("Normal");

        pnlNormalMap.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlNormalMapLayout = new javax.swing.GroupLayout(pnlNormalMap);
        pnlNormalMap.setLayout(pnlNormalMapLayout);
        pnlNormalMapLayout.setHorizontalGroup(
            pnlNormalMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlNormalMapLayout.setVerticalGroup(
            pnlNormalMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        btnNormalMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/text_16.png"))); // NOI18N
        btnNormalMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalMapActionPerformed(evt);
            }
        });

        btnEliminaMapaNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/delete_16.png"))); // NOI18N
        btnEliminaMapaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaMapaNormalActionPerformed(evt);
            }
        });

        txtMU_Normal.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        txtMU_Normal.setText("1");
        txtMU_Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMU_NormalActionPerformed(evt);
            }
        });

        txtMV_Normal.setText("1");
        txtMV_Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMV_NormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTamCelda)
                    .addComponent(txtMinY)
                    .addComponent(txtMaxY)
                    .addComponent(txtOffset)
                    .addComponent(pnlTexture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(pnlNormalMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlMapaDifuso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNormalMap, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminaMapaNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMU_Normal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMV_Normal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSetMapaDifuso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminaMapaDifuso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMU_Difusa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMV_Difusa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(pnlTexture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTamCelda, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(pnlMapaDifuso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSetMapaDifuso)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMU_Difusa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMV_Difusa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEliminaMapaDifuso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(pnlNormalMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEliminaMapaNormal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMU_Normal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNormalMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMV_Normal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTextureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTextureMouseClicked
        pnlTexture.getGraphics().drawImage(imagen, 0, 0, this);
    }//GEN-LAST:event_pnlTextureMouseClicked

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos soportados", "png", "jpg", "jpeg", "bmp", "gif"));
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            try {
                imagen = ImageIO.read(chooser.getSelectedFile());

                imagen2 = ImgUtil.escalarSuave(imagen, pnlTexture.getWidth(), pnlTexture.getHeight());
                pnlTexture.paint(pnlTexture.getGraphics());

                //                if (activeMaterial.getMapaDifusa() != null) {
                //
                //                } else {
                //
                //                }
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void txtMaxYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxYActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        aplicarCambios();
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void pnlMapaDifusoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMapaDifusoMouseClicked

    }//GEN-LAST:event_pnlMapaDifusoMouseClicked

    private void txtMU_DifusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMU_DifusaActionPerformed

    }//GEN-LAST:event_txtMU_DifusaActionPerformed

    private void btnSetMapaDifusoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetMapaDifusoActionPerformed

        //            chooser.setCurrentDirectory(new File(QGlobal.RECURSOS));
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos soportados", "png", "jpg", "jpeg", "bmp", "gif"));
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            try {
                textura = new QTextura(ImageIO.read(chooser.getSelectedFile()));
                mapaDifusoActual = textura.getImagen(new Dimension(pnlMapaDifuso.getWidth(), pnlMapaDifuso.getHeight()));

                pnlMapaDifuso.paint(pnlMapaDifuso.getGraphics());

                //                if (activeMaterial.getMapaDifusa() != null) {
                //
                //                } else {
                //
                //                }
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnSetMapaDifusoActionPerformed

    private void btnEliminaMapaDifusoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaMapaDifusoActionPerformed
        textura = null;
    }//GEN-LAST:event_btnEliminaMapaDifusoActionPerformed

    private void txtMV_DifusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMV_DifusaActionPerformed
    }//GEN-LAST:event_txtMV_DifusaActionPerformed

    private void btnNormalMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalMapActionPerformed

        chooser.setFileFilter(new FileNameExtensionFilter("Archivos soportados", "png", "jpg", "jpeg", "bmp", "gif"));
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            try {
                texturaNormal = new QTextura(ImageIO.read(chooser.getSelectedFile()));
                mapaNormalActual = texturaNormal.getImagen(new Dimension(pnlNormalMap.getWidth(), pnlNormalMap.getHeight()));
                pnlNormalMap.paint(pnlNormalMap.getGraphics());
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnNormalMapActionPerformed

    private void btnEliminaMapaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaMapaNormalActionPerformed

    }//GEN-LAST:event_btnEliminaMapaNormalActionPerformed

    private void txtMU_NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMU_NormalActionPerformed

    }//GEN-LAST:event_txtMU_NormalActionPerformed

    private void txtMV_NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMV_NormalActionPerformed

    }//GEN-LAST:event_txtMV_NormalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEliminaMapaDifuso;
    private javax.swing.JButton btnEliminaMapaNormal;
    private javax.swing.JButton btnNormalMap;
    private javax.swing.JButton btnSetMapaDifuso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlMapaDifuso;
    private javax.swing.JPanel pnlNormalMap;
    private javax.swing.JPanel pnlTexture;
    private javax.swing.JTextField txtMU_Difusa;
    private javax.swing.JTextField txtMU_Normal;
    private javax.swing.JTextField txtMV_Difusa;
    private javax.swing.JTextField txtMV_Normal;
    private javax.swing.JTextField txtMaxY;
    private javax.swing.JTextField txtMinY;
    private javax.swing.JTextField txtOffset;
    private javax.swing.JTextField txtTamCelda;
    // End of variables declaration//GEN-END:variables
}
