/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.qoopo.engine3d.editor.entidad.componentes.geometria;

import net.qoopo.engine3d.componentes.geometria.primitivas.formas.QToro;

/**
 *
 * @author alberto
 */
public class PnlToro extends javax.swing.JPanel {

    private QToro toro;

    /**
     * Creates new form PnlCubo
     */
    public PnlToro(QToro toro) {
        initComponents();
        this.toro = toro;

        txtRadio1.setText(String.valueOf(toro.getRadio1()));
        txtRadio2.setText(String.valueOf(toro.getRadio2()));
    }

    private void aplicarCambios() {
        toro.setRadio1(Float.parseFloat(txtRadio1.getText()));
        toro.setRadio2(Float.parseFloat(txtRadio2.getText()));
        toro.construir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRadio1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRadio2 = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Toro"));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel1.setText("Radio 1:");

        txtRadio1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        txtRadio1.setText("1");
        txtRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRadio1ActionPerformed(evt);
            }
        });
        txtRadio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRadio1KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel2.setText("Radio 2:");

        txtRadio2.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        txtRadio2.setText("1");
        txtRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRadio2ActionPerformed(evt);
            }
        });
        txtRadio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRadio2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(txtRadio1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(txtRadio2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRadio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRadio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadio1ActionPerformed
        aplicarCambios();
    }//GEN-LAST:event_txtRadio1ActionPerformed

    private void txtRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadio2ActionPerformed
        aplicarCambios();
    }//GEN-LAST:event_txtRadio2ActionPerformed

    private void txtRadio1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRadio1KeyReleased
        aplicarCambios();        // TODO add your handling code here:
    }//GEN-LAST:event_txtRadio1KeyReleased

    private void txtRadio2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRadio2KeyReleased
        aplicarCambios();        // TODO add your handling code here:
    }//GEN-LAST:event_txtRadio2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtRadio1;
    private javax.swing.JTextField txtRadio2;
    // End of variables declaration//GEN-END:variables
}
