/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.qoopo.engine3d.editor.entidad.componentes.fisica.restricciones;

import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import net.qoopo.engine3d.componentes.QComponente;
import net.qoopo.engine3d.componentes.QEntidad;
import net.qoopo.engine3d.componentes.fisica.dinamica.QObjetoRigido;
import net.qoopo.engine3d.componentes.fisica.restricciones.QRestriccionBisagra;
import net.qoopo.engine3d.core.escena.QEscena;

/**
 *
 * @author alberto
 */
public class PnlFisRestriccionBisagra extends javax.swing.JPanel {

    private QRestriccionBisagra componente;
    private Map<String, QObjetoRigido> mapa = new HashMap<String, QObjetoRigido>();

    /**
     * Creates new form PnlCubo
     */
    public PnlFisRestriccionBisagra(QRestriccionBisagra componente) {
        initComponents();
        this.componente = componente;

        DefaultComboBoxModel modelo = new DefaultComboBoxModel<>();
        for (QEntidad entidad : QEscena.INSTANCIA.getListaEntidades()) {
            for (QComponente comp : entidad.getComponentes()) {
                if (comp instanceof QObjetoRigido) {
                    modelo.addElement(entidad.getNombre());
                    mapa.put(entidad.getNombre(), (QObjetoRigido) comp);
                }
            }
        }
        cboFisico.setModel(modelo);
          if (componente.getB() != null) {
            cboFisico.setSelectedItem(componente.getB().entidad.getNombre());
        }
        aplicarCambios();
//        cboFisico.setSelectedItem(forma.getMalla().nombre);
//        txtRadio.setText(String.valueOf(esfera.getRadio()));
    }

    private void aplicarCambios() {
        componente.setB(mapa.get(cboFisico.getSelectedItem().toString()));
//        componente.setRadio(Float.parseFloat(txtRadio.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboFisico = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Restricción Bisagra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 9))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel1.setText("Cuerpo físico atado:");

        cboFisico.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        cboFisico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFisicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
            .addComponent(cboFisico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFisicoActionPerformed
        aplicarCambios();
    }//GEN-LAST:event_cboFisicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboFisico;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
